/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-04-24 14:48:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dao.doctorDao;
import com.entity.doctor;
import com.entity.appointment;
import java.util.List;
import com.Database.DBConnect;
import com.dao.appointmentDao;

public final class patient1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/admin/../component/allcss.jsp", Long.valueOf(1680856714827L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1680783039081L));
    _jspx_dependants.put("jar:file:/C:/Users/Gaurav/Desktop/Hospital%20Management%20System%20Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Hospital_Management_System/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/admin/navbar.jsp", Long.valueOf(1681472424198L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dao.doctorDao");
    _jspx_imports_classes.add("com.entity.doctor");
    _jspx_imports_classes.add("com.entity.appointment");
    _jspx_imports_classes.add("com.Database.DBConnect");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.dao.appointmentDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Patient page</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".paint-card {\r\n");
      out.write("	box-shadow: 10px 10px 5px 0px rgba(0, 0, 0, 0.75);\r\n");
      out.write("	-webkit-box-shadow: 10px 10px 5px 0px rgba(0, 0, 0, 0.75);\r\n");
      out.write("	-moz-box-shadow: 10px 10px 5px 0px rgba(0, 0, 0, 0.75);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".back-img {\r\n");
      out.write("	background-image: url(\"../img/h19.jpg\");\r\n");
      out.write("	background-repeat: no-repeat;\r\n");
      out.write("	height: 95vh;\r\n");
      out.write("	width: 100v;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body class=\"back-img\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("<nav class=\"navbar navbar-expand-lg p-2\" style=\"background: #b1a7a6\">\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<a class=\"navbar-brand fw-bold\" href=\"#\"><img\r\n");
      out.write("			src=\"../img/swastik.png\"\r\n");
      out.write("			style=\"height: 25px; width: 25px; margin: 4px\"> SWASTIK\r\n");
      out.write("			SANATORIUM</a>\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("			data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("			aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("			aria-label=\"Toggle navigation\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("			<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link active fw-bold\"\r\n");
      out.write("					aria-current=\"page\" href=\"index.jsp\"><i\r\n");
      out.write("						class=\"fa-solid fa-right-to-bracket\"></i>HOME</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link active fw-bold\"\r\n");
      out.write("					aria-current=\"page\" href=\"doctor.jsp\">ADD DOCTOR</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link active fw-bold\"\r\n");
      out.write("					aria-current=\"page\" href=\"viewDoctor.jsp\"> VIEW DOCTOR DETAILS</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link active fw-bold\"\r\n");
      out.write("					aria-current=\"page\" href=\"patient1.jsp\">PATIENT</a></li>\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("			<form class=\"d-flex mx-5\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"btn-group dropleft\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-danger\">Action</button>\r\n");
      out.write("					<button type=\"button\"\r\n");
      out.write("						class=\"btn btn-danger dropdown-toggle dropdown-toggle-split\"\r\n");
      out.write("						data-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("						<span class=\"sr-only\">Toggle Dropdown</span>\r\n");
      out.write("					</button>\r\n");
      out.write("					<div class=\"dropdown-menu\">\r\n");
      out.write("						<a class=\"dropdown-item\" href=\"../adminLogout\">LogOut</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container-fluid p-3\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("			<!--inside a row making a div of col-md-10  -->\r\n");
      out.write("			<div class=\"col-md-12 \">\r\n");
      out.write("\r\n");
      out.write("				<!-- card inside the container  -->\r\n");
      out.write("				<div class=\"card paint-card mt-5 mb-5\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<!--card body  -->\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<p class=\"text-center fs-3\">Patient Details</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<!--  adding a table inside the card body-->\r\n");
      out.write("						<table class=\"table table-dark\">\r\n");
      out.write("							<thead>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th scope=\"col\">Name</th>\r\n");
      out.write("									<th scope=\"col\">Gender</th>\r\n");
      out.write("									<th scope=\"col\">Age</th>\r\n");
      out.write("									<th scope=\"col\">Date(App.)</th>\r\n");
      out.write("									<th scope=\"col\">email</th>\r\n");
      out.write("									<th scope=\"col\">cell No.</th>\r\n");
      out.write("									<th scope=\"col\">Disease</th>\r\n");
      out.write("									<th scope=\"col\">Doctor Name</th>\r\n");
      out.write("									<th scope=\"col\">Address</th>\r\n");
      out.write("									<th scope=\"col\">Status</th>\r\n");
      out.write("\r\n");
      out.write("								</tr>\r\n");
      out.write("							</thead>\r\n");
      out.write("							<tbody>\r\n");
      out.write("\r\n");
      out.write("								<!-- using the scriptlet tag to make appointmentDao object so that we can call the getAppointment Detail method \r\n");
      out.write("							so that we can show the appointment details inside the table body  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								");

									appointmentDao apDaaDao = new appointmentDao(DBConnect.getConnection());
								List<appointment> list= apDaaDao.getAppointmentDetails();
								doctorDao d1=new doctorDao(DBConnect.getConnection());
								
								
								//iska matlab hota hai ki for every object of appointment type in list 
								// hai uske liye iterate karo poora list .(x works as a reference variable for appointment
										
								for(appointment x:list){
									doctor d2=d1.fetchDoctorDetailsbyId(x.getDoctorId());
									
									
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("									<tr>\r\n");
      out.write("\r\n");
      out.write("									<td>");
      out.print(x.getFullName() );
      out.write("</td>\r\n");
      out.write("									<td>");
      out.print(x.getGender()  );
      out.write("</td>\r\n");
      out.write("									<td>");
      out.print(x.getAge()  );
      out.write("</td>\r\n");
      out.write("									<td>");
      out.print(x.getAppointmentDate()  );
      out.write("</td>\r\n");
      out.write("									<td>");
      out.print(x.getEmail()  );
      out.write("</td>\r\n");
      out.write("									<td>");
      out.print(x.getNumber()  );
      out.write("</td>\r\n");
      out.write("									<td>");
      out.print( x.getDisease() );
      out.write("</td>\r\n");
      out.write("									<td>");
      out.print(d2.getFullName()  );
      out.write("</td>\r\n");
      out.write("									<td>");
      out.print( x.getFullAddres() );
      out.write("</td>\r\n");
      out.write("									<td>");
      out.print(x.getStatus()  );
      out.write("</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("									\r\n");
      out.write("								");
}
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								\r\n");
      out.write("\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("						<!-- table ends here -->\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
